### PR TITLE
Add rhtap dockerfile with allowed image references

### PR DESCRIPTION
**Pull request by gparvin**
See the details in the associated task.

Refs:
 - https://issues.redhat.com/browse/ACM-7178

### CODE REVIEW

**Comment by dhaiducek** [comment]
I'm not sure the location or name of the Dockerfile is configurable (at least it wasn't last I knew). I'm not sure the background on the issue nor whether this is feasible, but can the location just be updated upstream to `registry.access.redhat.com`?

```Dockerfile
FROM registry.ci.openshift.org/stolostron/builder:go1.20-linux AS builder
```

https://github.com/open-cluster-management-io/governance-policy-addon-controller/blob/c1e255e4bb58eec0f02462c4c27d9e8d638e958c/build/Dockerfile#L4

**Comment by dhaiducek** [comment]
Oh, nevermind--sorry. I see the pattern from Hypershift now.

**Comment by dhaiducek** [comment]
And Prow would be unaffected if RHTAP is referencing an entirely different build file, so that's good (though I'm not a fan of the risk for skew there, but it seems that's unavoidable).

**Comment by gparvin** [comment]
Looks like they don't have go 1.20 yet.  https://catalog.redhat.com/software/containers/ubi9/go-toolset/61e5c00b4ec9945c18787690?gs&q=go-too

**Comment by gparvin** [comment]
/hold
Waiting for golang tooling to be available for rhtap

**Comment by gparvin** [comment]
@dhaiducek Do you know what happened to the RHTAP tests that used to run in PRs?

**Comment by dhaiducek** [comment]
> @dhaiducek Do you know what happened to the RHTAP tests that used to run in PRs?

It should be running as far as I know. The RHTAP console is down, so maybe there's an outage?

**Comment by dhaiducek** [comment]
@gparvin Have you tried rebasing this PR? It might not be running because it doesn't like that the branch is behind, maybe?

**Pull request closed without merging**
