### PR TITLE
Fix flaky Kind test minimum issue

### PR DESCRIPTION
**Pull request by yiraeChristineKim**

### CODE REVIEW

**Comment by dhaiducek** [comment]
@yiraeChristineKim Since it's flaky, do you mind if we re-run the tests 2 more times to see whether it happens again before we merge it?

**Comment by yiraeChristineKim** [comment]
> @yiraeChristineKim Since it's flaky, do you mind if we re-run the tests 2 more times to see whether it happens again before we merge it?

5 times good good!! also I tested A LOT of times when it was draft pr

**Pull request merged**
