### PR TITLE
Add rhtap dockerfile with allowed image references

### PR DESCRIPTION
**Pull request by gparvin**
See the details in the associated task.

Refs:
 - https://issues.redhat.com/browse/ACM-7178

### CODE REVIEW

**Comment by dhaiducek** [comment]
```
[1/2] STEP 6/6: RUN make build
CGO_ENABLED=1 go build -o build/_output/bin/governance-policy-addon-controller main.go
Go compliance shim [296] [][]: assessment: CGO_ENABLED=1
Go compliance shim [296] [][]: assessment: dynamic linking
Go compliance shim [296] [][]: skipping forced compliance due to broad exemption
Go compliance shim [296] [][]: EXEMPT: 1


Go compliance shim [296] [][]: final command line arguments: "build" "-o" "build/_output/bin/governance-policy-addon-controller" "main.go" 

Go compliance shim [296] [][]: invoking real go binary
go: inconsistent vendoring in /go/src/github.com/stolostron/governance-policy-addon-controller:
	github.com/blang/semver/v4@v4.0.0: is explicitly required in go.mod, but not marked as explicit in vendor/modules.txt
	. . . (many similar lines) . . .

	To ignore the vendor directory, use -mod=readonly or -mod=mod.
	To sync the vendor directory, run:
		go mod vendor
Go compliance shim [296] [][]: Exited with: 1
make: *** [Makefile:112: build] Error 1
subprocess exited with status 2
subprocess exited with status 2
Error: building at STEP "RUN make build": exit status 2
```

**Comment by dhaiducek** [comment]
I'm not familiar with the `openshift-golang-builder`, but looking at the logs it seems like it's doing some sort of validation of the build?

**Comment by gparvin** [comment]
Note: I had to add `go mod vendor` to the rhtap dockerfile to get it to build due to a "compliance shim" that is built into the go tooling being used.

**Review by dhaiducek — APPROVED** [review]
I'm not sure the effect of having `go mod vendor` in there, but it seems that's how they want it! Thanks for working this one out, @gparvin!

**Pull request merged**
